export const themes = [
  { id: "neon-purple", name: "Neon Purple", vars: { "--accent": "#8b5cf6", "--accent-2": "#22d3ee", "--bg": "#0b0b18" } },
  { id: "thriller-night", name: "Thriller Night", vars: { "--accent": "#f97316", "--accent-2": "#ef4444", "--bg": "#120b12" } },
  { id: "chrome-stage", name: "Chrome Stage", vars: { "--accent": "#e2e8f0", "--accent-2": "#38bdf8", "--bg": "#0a0f16" } },
  { id: "retro-vhs", name: "Retro VHS", vars: { "--accent": "#ec4899", "--accent-2": "#facc15", "--bg": "#120c1a" } },
  { id: "blue-spotlight", name: "Blue Spotlight", vars: { "--accent": "#3b82f6", "--accent-2": "#22d3ee", "--bg": "#0b1120" } },
  { id: "gold-finale", name: "Gold Finale", vars: { "--accent": "#f59e0b", "--accent-2": "#f472b6", "--bg": "#11100c" } },
];

export const levels = [
  { id: 1, name: "Club Intro", speedPxPerSec: 260, density: 0.7, wPerfectMs: 80, wGoodMs: 140, wOkayMs: 210, timeSec: 75 },
  { id: 2, name: "City Lights", speedPxPerSec: 290, density: 0.8, wPerfectMs: 80, wGoodMs: 135, wOkayMs: 200, timeSec: 75 },
  { id: 3, name: "Neon Tour", speedPxPerSec: 320, density: 0.9, wPerfectMs: 75, wGoodMs: 130, wOkayMs: 190, timeSec: 80 },
  { id: 4, name: "Arena Pop", speedPxPerSec: 350, density: 1.0, wPerfectMs: 70, wGoodMs: 125, wOkayMs: 185, timeSec: 80 },
  { id: 5, name: "Stadium Shine", speedPxPerSec: 380, density: 1.1, wPerfectMs: 70, wGoodMs: 120, wOkayMs: 180, timeSec: 85 },
  { id: 6, name: "Moonwalk Rush", speedPxPerSec: 410, density: 1.2, wPerfectMs: 68, wGoodMs: 118, wOkayMs: 175, timeSec: 85 },
  { id: 7, name: "Bad Groove", speedPxPerSec: 440, density: 1.25, wPerfectMs: 65, wGoodMs: 115, wOkayMs: 170, timeSec: 90 },
  { id: 8, name: "Thriller Night", speedPxPerSec: 470, density: 1.3, wPerfectMs: 62, wGoodMs: 110, wOkayMs: 165, timeSec: 90 },
  { id: 9, name: "Billie Jean Blitz", speedPxPerSec: 500, density: 1.35, wPerfectMs: 60, wGoodMs: 108, wOkayMs: 160, timeSec: 90 },
  { id: 10, name: "Finale Prime", speedPxPerSec: 540, density: 1.4, wPerfectMs: 58, wGoodMs: 105, wOkayMs: 155, timeSec: 95 },
];

export const tracks = [
  {
    id: "neon-pulse",
    name: "Neon Pulse",
    bpm: 128,
    instrument: "Synthwave",
    apiQuery: "Neon Pulse",
  },
  {
    id: "sunset-guitar",
    name: "Sunset Guitar",
    bpm: 96,
    instrument: "Acoustic Guitar",
    apiQuery: "Sunset Guitar",
  },
  {
    id: "city-drums",
    name: "City Drums",
    bpm: 144,
    instrument: "Drumline",
    apiQuery: "City Drums",
  },
  {
    id: "retro-keys",
    name: "Retro Keys",
    bpm: 112,
    instrument: "Electric Piano",
    apiQuery: "Retro Keys",
  },
  {
    id: "orchestral-rise",
    name: "Orchestral Rise",
    bpm: 84,
    instrument: "Strings & Brass",
    apiQuery: "Orchestral Rise",
  },
  {
    id: "bassline-rush",
    name: "Bassline Rush",
    bpm: 160,
    instrument: "Electronic Bass",
    apiQuery: "Bassline Rush",
  },
];

export const trackProfiles = {
  "neon-pulse": {
    segments: [
      { durationSec: 12, spacingMs: 520, directions: ["left", "down", "right", "up"] },
      { durationSec: 12, spacingMs: 430, directions: ["left", "right", "left", "right", "up"] },
      { durationSec: 10, spacingMs: 380, directions: ["down", "left", "right", "up", "right"] },
      { durationSec: 10, spacingMs: 450, directions: ["left", "down", "right", "up"] },
    ],
  },
  "sunset-guitar": {
    segments: [
      { durationSec: 16, spacingMs: 690, directions: ["left", "up", "right", "down"] },
      { durationSec: 14, spacingMs: 620, directions: ["left", "right", "up", "down"] },
      { durationSec: 12, spacingMs: 560, directions: ["left", "down", "right", "up"] },
    ],
  },
  "city-drums": {
    segments: [
      { durationSec: 10, spacingMs: 420, directions: ["down", "down", "left", "right", "up"] },
      { durationSec: 12, spacingMs: 340, directions: ["left", "right", "left", "right", "down", "up"] },
      { durationSec: 10, spacingMs: 370, directions: ["down", "left", "right", "down", "up"] },
    ],
  },
  "retro-keys": {
    segments: [
      { durationSec: 14, spacingMs: 600, directions: ["left", "up", "right", "up"] },
      { durationSec: 10, spacingMs: 500, directions: ["left", "right", "down", "up"] },
      { durationSec: 10, spacingMs: 460, directions: ["left", "down", "right", "up"] },
    ],
  },
  "orchestral-rise": {
    segments: [
      { durationSec: 18, spacingMs: 760, directions: ["left", "up", "right", "down"] },
      { durationSec: 12, spacingMs: 620, directions: ["down", "left", "right", "up"] },
      { durationSec: 12, spacingMs: 520, directions: ["left", "right", "up", "down", "up"] },
    ],
  },
  "bassline-rush": {
    segments: [
      { durationSec: 8, spacingMs: 360, directions: ["left", "right", "left", "right", "down"] },
      { durationSec: 10, spacingMs: 320, directions: ["down", "left", "right", "up", "down", "up"] },
      { durationSec: 12, spacingMs: 340, directions: ["left", "right", "left", "right", "up"] },
    ],
  },
  default: {
    segments: [
      { durationSec: 12, spacingMs: 560, directions: ["left", "down", "right", "up"] },
      { durationSec: 10, spacingMs: 520, directions: ["left", "right", "down", "up"] },
      { durationSec: 10, spacingMs: 540, directions: ["left", "down", "right", "up"] },
    ],
  },
};

export const choreography = {
  "billie-jean": {
    baseAnim: "idle",
    intensityByLevel: {
      low: 1,
      mid: 2,
      high: 3,
    },
    triggers: {
      perfect: ["spin", "pose", "moonwalk"],
      good: ["step_left", "step_right"],
      okay: ["step_left", "idle"],
      miss: ["stumble", "idle"],
    },
  },
  default: {
    baseAnim: "idle",
    intensityByLevel: { low: 1, mid: 2, high: 3 },
    triggers: {
      perfect: ["spin", "pose"],
      good: ["step_left", "step_right"],
      okay: ["step_left", "idle"],
      miss: ["stumble", "idle"],
    },
  },
};

export const globalConfigDefaults = {
  featuredLevelId: 1,
  featuredTrackId: "neon-pulse",
  globalThemeId: "neon-purple",
  announcementBannerText: "Welcome to Moonwalk Mania.",
  leaderboardRules: "Fair play only. Scores validated server-side.",
  maintenanceMode: false,
  choreoOverrides: {},
};

export const commandList = [
  "help",
  "commands",
  "whoami",
  "permissions",
  "sync status",
  "sync reconnect",
  "config draft show",
  "config draft set",
  "config draft undo",
  "config draft reset",
  "config publish",
  "config rollback",
  "config history list",
  "config get",
  "announce set",
  "announce clear",
  "featured level set",
  "featured track set",
  "theme global set",
  "maintenance on",
  "maintenance off",
  "export settings",
  "import settings",
  "diag state",
  "diag network",
  "diag cache",
  "ui toast",
  "ui theme",
  "ui sidebar",
  "ui header",
  "ui hud",
  "ui motion",
  "leaderboard refresh",
  "leaderboard purge",
  "profile get",
  "profile set",
  "score submit",
  "score validate",
  "score simulate",
  "dancer mode",
  "dancer choreo",
  "dancer reset",
  "level list",
  "track list",
  "settings list",
  "settings save",
  "settings load",
  "settings reset",
  "admin unlock",
  "admin lock",
  "log clear",
  "log copy",
  "log export",
  "help categories",
  "help gameplay",
  "help admin",
  "help sync",
  "help leaderboard",
  "help settings",
  "help profile",
  "help debug",
  "network offline",
  "network online",
  "network retry",
  "draft status",
  "draft apply",
  "draft discard",
  "draft publish",
  "draft preview",
  "history list",
  "history rollback",
  "rollback last",
  "rollback version",
  "config validate",
  "config diff",
  "config export",
  "config import",
  "config subscribe",
  "config unsubscribe",
  "maintenance status",
  "status",
  "about",
  "version",
  "ping",
  "time now",
  "echo",
  "set banner",
  "clear banner",
  "featured level",
  "featured track",
  "theme list",
  "theme set",
  "theme current",
  "dancer list",
  "dancer toggle",
  "controls list",
  "controls reset",
  "console help",
  "console clear",
  "console history",
  "console copy",
  "console export",
  "user list",
  "user role",
  "user ban",
  "user unban",
  "user warn",
  "user mute",
  "user unmute",
  "audit log",
  "audit export",
  "moderation queue",
  "moderation clear",
  "moderation review",
  "sync history",
  "sync stats",
  "sync latency",
  "sync ping",
  "cache clear",
  "cache status",
  "cache refresh",
  "cache preload",
  "preview draft",
  "preview published",
  "preview reset",
];
